server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tigerMoon/spConfig-repo
          searchPaths: client1,client2
          basedir: target/config
#      enabled: false