server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tigerMoon/spring-cloud-example.git
          searchPaths: spConfig-repo/client1,spConfig-repo/client2
          basedir: target/config
          default-label: master
      enabled: true


